# -------------------------------
# Dockercompose f체r das Read-Team-Lab
# Erzeugt einen Container f체r das Read-Team-Lab
# Dieser Container enth채lt Tools f체r Angriffe und eine Wordlist
# -------------------------------
# Author: Jann (Janis)
services:
  target:
    build:
      context: .
      dockerfile: Dockerfile.target
    container_name: ssh-target
    ports:
      - "2222:22"    # SSH
      - "8080:80"    # HTTP
      - "8443:443"   # HTTPS
    networks:
      - lab_net

  attacker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: red-attacker
    volumes:
      - ./logs:/logs
    depends_on:
      target:
        condition: service_started
    networks:
      - lab_net
    command: ["/attack.sh"]
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "512M"

networks:
  lab_net:
    driver: bridge